name: Compile AL Application
description: Compile the AL application in the specified container.

inputs:
  containerName:
    description: "The name of the Business Central container."
    required: true
  artifactName:
    description: "The name of the artifact."
    required: true
  BC_PASSWORD:
    description: "bc password"
    required: true  
  BC_USERNAME:
    description: "bc username"
    required: true  
  LICENSE_FILE:
    description: "bc license file"
    required: true  

runs:
  using: "composite"
  steps:
    - name: Compile Application
      shell: pwsh
      env:
        containerName: ${{ inputs.containerName}}
        artifactName: ${{ inputs.artifactName}}
        BC_PASSWORD: ${{ inputs.BC_PASSWORD}}
        BC_USERNAME: ${{ inputs.BC_USERNAME}}
        LICENSE_FILE: ${{ inputs.LICENSE_FILE}}


      run: |
        Write-Host "Debugging Secrets"
        Write-Host "BC_USERNAME: $env:BC_USERNAME"
        Write-Host "BC_PASSWORD: $env:BC_PASSWORD"
        Write-Host "LICENSE_FILE: $env:LICENSE_FILE"
        Install-Module -Name bccontainerhelper -Force
        $module = Get-InstalledModule -Name bccontainerhelper -ErrorAction Ignore
        Write-Host "BcContainerHelper $($module.Version.ToString()) installed"

        $containerName = $env:containerName
        $artifactName = $env:artifactName
        if (-not $env:BC_USERNAME) {
             Write-Host "Error: BC_USERNAME is empty or not set."
            exit 1
        }
        $username = $env:BC_USERNAME
        if (-not $env:BC_PASSWORD) {
             Write-Host "Error: BC_PASSWORD is empty or not set."
            exit 1
        }
        $password = ConvertTo-SecureString $env:BC_PASSWORD -AsPlainText -Force
        $credential = New-Object System.Management.Automation.PSCredential ($username, $password)

        $licenseFile = $env:LICENSE_FILE


        try { 
            Get-BcContainerId -containerName $containerName
            Start-BcContainer -containerName $containerName
        }
        catch {  
            $artifactUrl = Get-BCArtifactUrl -country w1 -select Latest -storageAccount bcartifacts -type Sandbox

            $AdditionalParameters = @()
            $AdditionalParameters += '--volume "{0}:{1}"' -f $RepositoryDirectory, 'c:\sources'
            
            $Params = @{
              accept_eula = $true
              artifactUrl = $artifactUrl
              containerName = $containerName
              auth = 'NavUserPassword'
              credential = $credential
              isolation = 'process'
              memoryLimit = '8GB'
              accept_outdated = $true
              useBestContainerOS = $true
              additionalParameters = $AdditionalParameters
            }
            
            New-BcContainer @Params -shortcuts None
        }

        # Increase app version
        $app = (Get-Content "app.json" -Encoding UTF8 | ConvertFrom-Json)
        $existingVersion = $app.version -as [version]
        $versionBuild = Get-Date -Format "yyyyMMdd"
        $versionRevision = Get-Date -Format "HHmmss"
        $nextVersion = [version]::new($existingVersion.Major, $existingVersion.Minor, $versionBuild, $versionRevision)
        $app.version = "$nextVersion"
        $app | ConvertTo-Json | Set-Content app.json
        Write-Host "##[section]Version increased to $nextVersion"

        # Compile app
        Write-Host "##[command]Compiling app" $app.Name $app.Version
        Compile-AppInBcContainer -appProjectFolder $RepositoryDirectory -containerName $containerName -credential $credential -GenerateReportLayout Yes -ReportSuppressedDiagnostics

        # Copy app to build staging directory
        Write-Host "##[section]Moving app to build staging directory"
        Copy-Item -Path (Join-Path $RepositoryDirectory -ChildPath("\output\" + $app.publisher + "_" + $app.Name + "_" + $app.Version + ".app")) -Destination $env:Build_StagingDirectory
        Write-Host "##[section]Staging directory $env:Build_StagingDirectory"

        # Update build pipeline number
        Write-Host "##vso[build.updatebuildnumber]$nextVersion"



        #increase app version
        $app = (Get-Content "app.json" -Encoding UTF8 | ConvertFrom-Json)
        $existingVersion = $app.version -as [version]
        $versionBuild = Get-Date -Format "yyyyMMdd"
        $versionRevision = Get-Date -Format "HHmmss"
        $nextVersion = [version]::new($existingVersion.Major, $existingVersion.Minor, $versionBuild, $versionRevision)
        $app.version = "$nextVersion"
        $app | ConvertTo-Json | Set-Content app.json
        write-host "##[section]Version increased to $nextVersion"
        #increase app version

        #compile app
        write-host "##[command]Compiling app" $app.Name $app.Version
        Compile-AppInBcContainer -appProjectFolder $RepositoryDirectory -containerName $ContainerName -credential $Credential -GenerateReportLayout Yes -ReportSuppressedDiagnostics
        #compile app

        #copy app to build staging directory
        write-host "##[section]Moving app to build staging directory"
        Copy-Item -Path (Join-Path $RepositoryDirectory -ChildPath("\output\" + $app.publisher + "_" + $app.Name + "_" + $app.Version + ".app")) -Destination $env:Build_StagingDirectory
        Copy-Item -Path (Join-Path $RepositoryDirectory -ChildPath("PublishApp.ps1")) -Destination $env:Build_StagingDirectory
        write-host "##[section]Staging directory $env:Build_StagingDirectory"
        #copy app to build staging directory

        #updating build pipeline number
        Write-Host "##vso[build.updatebuildnumber]$nextVersion"
        #updating build pipeline number 
              
