name: Checkout Repository
on:
  workflow_call:

jobs:
  checkout:
    runs-on: windows-latest
    environment: LocalizationSandbox

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true
