name: "Build and Deploy AL Application"

on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'feature/**'
      - 'promotion/**'
      - 'qa'
      - 'staging'
      - 'release/**'
      - 'prod'

permissions:
  contents: read

env:
  system_debug: true
  Build_StagingDirectory: ${{ github.workspace }}/Build/Staging

jobs:
  build-and-deploy:
    runs-on: windows-latest
   

    steps:
      # Repository'yi Checkout Et
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true

      # Docker Kurulumunu Kontrol Et
      - name: Check Docker Installation
        shell: pwsh
        run: |
          if (-Not (docker --version)) {
            Write-Host "Docker is not installed!"
            exit 1
          } else {
            Write-Host "Docker is installed and running."
          }

      # Docker Servisini Başlat
      - name: Start Docker Service
        shell: pwsh
        run: |
          Start-Service docker
          Write-Host "Docker service started successfully."

      # AL Uygulamasını Derle
      - name: Compile AL Application
        uses: ./.github/actions/compile-app
        with:
          containerName: ${{ vars.CONTAINERNAME }}
          artifactName: ${{ vars.ARTIFACTNAME }}

      # AL Uygulamasını Yayınla
      - name: Publish AL Application
        uses: ./.github/actions/publish-app
        with:
          containerName: ${{ vars.CONTAINERNAME }}
          artifactName: ${{ vars.ARTIFACTNAME }}

      # Derleme Artifaktlarını Yükle
      - name: Publish Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: ${{ env.Build_StagingDirectory }}
