name: Build and Deploy AL Application

on:
  workflow_dispatch:
  pull_request:
    branches:
       - 'feature/**'
       - 'promotion/**'
       - 'qa'
       - 'staging'
       - 'release/**'
       - 'prod'

permissions:
  contents: read

env:
  system_debug: true
  Build_StagingDirectory: ${{ github.workspace }}/Build/Staging
  ACTIONS_RUNNER_DEBUG: true
  ACTIONS_STEP_DEBUG: true

jobs:
  checkout-repository:
    uses: KRYAYKN/PargePipelines/.github/workflows/checkout-repository.yaml@promotion/staging

  prepare-docker:
    needs: checkout-repository
    uses: KRYAYKN/PargePipelines/.github/workflows/prepare-docker.yaml@promotion/staging

  compile-and-prepare:
    needs: prepare-docker
    uses: KRYAYKN/PargePipelines/.github/workflows/compile-app.yaml@promotion/staging
    with:
      containerName: ${{ vars.CONTAINERNAME }}
      artifactName: ${{ vars.ARTIFACTNAME }}
      BC_USERNAME: ${{ secrets.BC_USERNAME }}
      BC_PASSWORD: ${{ secrets.BC_PASSWORD }}
      LICENSE_FILE: ${{ secrets.LICENSE_FILE }}

  publish-app:
    needs: compile-and-prepare
    uses: KRYAYKN/PargePipelines/.github/workflows/publish-app.yaml@promotion/staging
    with:
      containerName: ${{ vars.CONTAINERNAME }}
      artifactName: ${{ vars.ARTIFACTNAME }}
      TENANT_ID: ${{ secrets.TENANT_ID }}
      REFRESHTOKEN: ${{ secrets.REFRESHTOKEN }}
      ENVIRONMENT: "LocalizationSandbox"

  publish-build-artifacts:
    needs: publish-app
    uses: KRYAYKN/PargePipelines/.github/workflows/publish-build-artifacts.yaml@mpromotion/staging
    with:
      artifactsDirectory: ${{ env.Build_StagingDirectory }}
