name: Prepare Docker
on:
  workflow_call:

jobs:
  prepare-docker:
    runs-on: windows-latest

    steps:
      - name: Check Docker Installation
        shell: pwsh
        run: |
          if (-Not (docker --version)) {
            Write-Host "Docker is not installed!"
            exit 1
          } else {
            Write-Host "Docker is installed and running."
          }

      - name: Start Docker Service
        shell: pwsh
        run: |
          Start-Service docker
          Write-Host "Docker service started successfully."
